### ISSUE TITLE
Ability to use native enum instead of separate table

### ISSUE THREAD

**Issue by mmahalwy** [stephenh/joist-ts#193]

**Comment by stephenh** [comment]
Hey @mmahalwy ; @chr1sjf0x on our team has been wanting this feature as well :-D 

We need to write some docs on it, but personally I'm generally convinced that the separate-table approach is better, although probably what's most important is that, within a given project/codebase, the project ideally picks just one or the other, instead of mixing pg enums w/ enum tables kinda onsey-twosy.

I'm not against Joist supporting both though, especially for existing PG schemas (although one of the also-not-yet-written non-goals of Joist is to bend over backwards supporting existing schemas, which a lot of the older Java ORMs always "had" to do, and makes the ORM's life much more complicated).

**Comment by mmahalwy** [comment]
@stephenh I agree that we should choose either one. Having the ability to support both would be most ideal. I'd imagine for folks coming from Prisma or other ORMs would have the enums defined as a type.

**Comment by mmahalwy** [comment]
Hey @stephenh I have some time over the holidays now and I'd love to help on this. Is the challenge here that the orm wont recognize native enums or is it the migration? I can dig around too

**Comment by stephenh** [comment]
@mmahalwy fwiw I do not have a super-structured approach here; what I'd personally do is:

1. Modify the integration-tests migration file to include a new pg enum, like `authors.favorite_shape` is `circle, square, triangle`
2. Run `yarn codegen` in `packages/integration-tests` and see what happens
   - If there are stack traces, go see why and fix them
   - If the codegen output is not as expected, look at the `generate...ts` files in `packages/codegen` to figure out why
3. Write a new `PostgresEnums.ts` in `integration-tests` that uses the new `Authors.favoriteShape` field

Right now the `EntityDbMetadata` has an `EnumField` / `enums` array of "enum table"-style data. Fwiw I'd probably leave that as-is, b/c it has a lot of features / codepaths that are likely specific to enum table-style output.

Instead you could add like a `PgEnumField` and `pgEnums` as new field types ... or _maybe_ put the pg enums fields into the existing `dbMetadata.primitives` array as `PrimitiveFields` but with like an `isEnum: true` / `enumValues: string[]` sort of options. It depends on how similar or not-similar the codegen output + runtime behavior of pg enums are / are not vs. regular primitives.

Then you'll probably need a copy/paste of `generateEnumFile` that is like `generatePgEnumFile`...
