### ISSUE TITLE
Allow passing ids to em.create

### ISSUE THREAD

**Issue by mmahalwy** [stephenh/joist-ts#203]
Take example:
```ts
const em = newEntityManager();
  const company = await em.create(Company, { name: 'company 1' });

  const person = await em.create(Person, {
    firstName: 'asdsd',
    email: 'MO@WITHSHEPHERD.COM',
    company: company, // <---- what does this do? 
  });
```

I noticed that we cannot set `companyId` on create of the `Product` entity. Is that intended?

**Comment by stephenh** [comment]
The "what does this do" line sets the associated id, i.e. it sets the `person.company_id` column, but correct, right now you have to set it by having the `Company` instance loaded, and not just setting `company: 1`.

That seems possible to support, but is not currently implemented.

**Comment by stephenh** [comment]
@mmahalwy fwiw @zgavin mentioned two things:

1) `em.create` is synchronous, so you don't need to `await` it in your examples
2) We have an `em.createOrUpdatePartial` that is asynchronous, and ironically because it is `async`, it can accept `id`s (b/c it internally resolves the `id` to the entity before calling `em.create`

  So like:

```
const person = await em.createOrUpdatePartial(Person, {
    firstName: 'asdsd',
    email: 'MO@WITHSHEPHERD.COM',
    company: companyId, 
  });
```

Should work. Note that the "partial" aspect means the type-safety isn't as strong as `em.create`, i.e. not all required fields are required in the `createOrUpdatePartial` version, but the validation rules/etc. will still run.

**Comment by mmahalwy** [comment]
@stephenh I can take this on if you point me in the right direction again :)

**Comment by stephenh** [comment]
Sure; so, I think this one is doable, but there is some nuance; right now `em.create` returns `New<T>`:

```
  /** Creates a new `type` and marks it as loaded, i.e. we know its collections are all safe to access in memory. */
  public create<T extends Entity, O extends OptsOf<T>>(type: EntityConstructor<T>, opts: O): New<T, O> {
    // The constructor will run setOpts which handles defaulting collections to the right state.
    return new type(this, opts) as New<T, O>;
  }
```

Where the `New` marks every reference/collection as loaded.

The idea here is that, if I just created an `Author`, then surely there are no books in the database pointing to this author yet, so we "just know" the `Author.books` collection can be marked as loaded.

Similarly, if you `const b = em.create(Book, { author: a1 })`, where `a1` is an `Author` instance, you can immediately do `b.author.get` w/o a load hint or an `await`.

However, this proposal is to allow passing `{ author: "a:1" }`, which given it's not an already-loaded entity, means that `em.create` cannot return `New<T>` anymore, which would be a pretty big breaking change, that I want to avoid.

That said, we may be able to provide an overload, i.e. something like:

```
  public create<T extends Entity, O extends OptsOf<T>>(type: EntityConstructor<T>, opts: O): New<T, O>;
  public create<T extends Entity, O extends OptsOf<T>>(type: EntityConstructor<T>, opts: AllowIds<O>): T;
  public create<T extends Entity, O extends OptsOf<T>>(type: EntityConstructor<T>, opts: O): New<T, O> {
    // The constructor will run setOpts which handles defaulting collections to the right state.
    return new type(this, opts) as New<T, O>;
  }
```

Where the new `AllowIds` is a mapped type that takes the existing `AuthorOpts` and, for any field that accepts entities, adds an `| IdOf<...>` union. Basically like what `AllowRelationsToBeIdsOrEntitiesOrPartials` does...although for some reason it operates on the entity type i.e. `Author` itself, instead of operating against the `AuthorOpts` types...not sure why...

So, that is step 1 (telling the type system that these relations are not loaded), after that is step 2, which is telling the runtime that these relations are not loaded. 

For this step2, right now `setOpts`, which is called from the `AuthorCodegen` constructor, has this line of code:

```
  if (calledFromConstructor) {
    getRelations(entity).forEach((v) => v.initializeForNewEntity());
  }
```

Which is what tells all relations "hey, if you want to, you can mark yourself as loaded now".

For `ManyToOneReferenceImpl`, we'd want to update it's `initializeForNewEntity` to, instead of unconditionally marking itself as loaded, to check if the current value inside of `entity.__orm.data` is a full entity (as it must be today) and then mark loaded=true, or if (after your change) it's just a tagged id, and if so leave loaded as false.

After doing these two things, I think everything should basically work.

I guess I wouldn't be entirely surprised if there are a few wrinkles after this, i.e. where newly created entities assume that their relations are only populated with full-entities and not just ids...but I can't think of anything at the moment...

(Also, just to be clear, the reasons for these changes is that `em.create` is synchronous, so when "a:1" is passed in opts, it cannot sneak in an `em.load` call to get the real `Author`; that said, we do already have `em.createOrUpdatePartial` which is async, so already accepts ids for relations, and so really the "easiest" workaround here is for your code to just use the existing `const newBook = await em.createOrUpdatePartial(...)` b/c it will accept IDs and already do what you want. At the expense of needing an `await`. That disclaimer/fwiw aside, it'd be great to have a more flexible `em.create` as well, so I'm still +1 to this idea.)

**Comment by mmahalwy** [comment]
@stephenh would you be open to having `em.create` be async?

**Comment by stephenh** [comment]
@mmahalwy hrm, no, not really; granted, Joist isn't used by 1,000s of applications or anything, so breaking changes are not out of the question, but our app uses the sync-ness of `em.create` quite a lot.

Also the factories i.e. `newAuthor` go through `newTestInstance` which goes through `em.create`, and it's a big ergonomics win for factories to be synchronous.

So, yeah, I'd prefer at best `em.create` overload (which should be doable AFAIU, just a little more nuanced) or at worst an additional `em.createSomeOtherName` method (i.e. a new `em.createPartial` could be `async`, just like the existing `createOrUpdatePartial`, but I'm not sure if the partial-ness is something you want to actively avoid).

**Comment by mmahalwy** [comment]
@stephenh totally see where youre coming from, although I think a find+replace to add `await` to where there's creates hopefully isnt too much. I think having `create` as async would match the rest of (and the more to come) methods on the em which all (AFAIK) happen to be async. Keeping it consistent would make for a better DX, and potentially solve this issue too

**Comment by stephenh** [comment]
If I thought `em.create` requiring `await` was an improvement, I would do the refactoring, but currently I don't. :-) 

To a certain extent, calling `em.create` is basically like calling a constructor, i.e. currently `const a = new Author(em, {})` and `const a = em.create(Author, {})` are essentially the same thing. And "requiring `await` just to create an object" doesn't seem great.

> happen to be async

`em.delete` and `em.touch` are both sync, but yes the majority of EM's functionality, `find` / `load` / `flush` requires wire calls.

Currently `em.create` and `em.delete` are sync with the rationale that they are not literally issuing wire calls / SQL statements; instead they are just telling `EntityManager` about an operation that will later be performed during `flush`.

Granted, we have `createOrUpdatePartial` which is `async`, but that's a special/dedicated utility method.

So, I think I'm still pushing a) just use `createOrUpdatePartial`, b) add an async overload to `create`, or c) `em.load` the IDs -> entities before calling `em.create`. Fwiw our super-generic CRUD infra could usually does a), and the more specific/special case CRUD handling does c).
