### ISSUE TITLE
detag via a config

### ISSUE THREAD

**Issue by mmahalwy** [stephenh/joist-ts#313]
Feature request: allow disabling tagging of ids via the config

**Comment by stephenh** [comment]
Out of curiosity, @mmahalwy what do specifically do you need this for?

Is it for matching existing Prisma style behavior of `author.toJSON()` --> has JSON with IDs that don't have ids and fields that have null?

If so...I'm wondering if maybe we could do something like:

1. Add a overload to `author.toJSON({ taggedIds: false })`, where you could explicitly request JSON behavior "sans tagged ids"

2. Have some sort of global `configureToJson({ taggedIds: false })` that would tell Joist's internal `toJSON` behavior to not use tagged ids, just for the `toJSON` output.

Just wondering if this (or other ideas) would be a more direct way of supporting your use case(s), instead of assuming we must support untagged ids.

(Granted, at some point users will probably ask for "author.id fields that are `number`s", again I'm sure for the legacy migration case of "all of our code assumes id is a `number`", at which point we'd be back to "well obviously numbers can't be tagged".) :thinking:

**Comment by mmahalwy** [comment]
@stephenh the goal here is to remove the usage of tagged ids that could end up in places outside the API. For example, if we are sending an email with an id to a model, we'd have to detag. Secondly, we arent using the graphql resolvers that are generated by joist. We use https://pothos-graphql.dev/. So we'd have to detag the ids ourselves for our graphql api. Lastly, for migrating into joist, this would be the migration much safer (since our app is used to having non-tagged ids).

**Comment by mmahalwy** [comment]
Lastly, I do agree with the number ids. For folks who'd want to migrate to joist, this could be a non-starter. Luckily we use uuids so we arent affected, but this is a legit concern

**Comment by stephenh** [comment]
@mmahalwy pretty sure we can close this out? Assuming so so closing pre-emptively :-)
