### ISSUE TITLE
Relation references within filters

### ISSUE THREAD

**Issue by brudil** [stephenh/joist-ts#680]
I'm a bit unsure here if I've hit a runtime error or lack of type-safety here.

Imagine a UserAccount entity with a FK to a Organisation entity.

```ts
em.findCount(
  UserAccount,
  {
    // Passing in the reference
    organisation: user.organisation, // ManyToOneReference<UserAccount, Organisation, never>
  }
);
```

The reference here does not create a TS warning about passing this in to the `FilterWithAlias`.

When executing this though, we get an error:

```
fieldName not found on organisation
```

Digging in to this, it's coming from QueryParser.ts:L158 iterating though the properties of the ManyToOneReference object.

I'm assuming this isn't a runtime bug and that relations should be loaded for use within filters?

**Comment by stephenh** [comment]
Huh, that is weird... that should be:

```
em.findCount(
  UserAccount, { organisation: user.organization.get } // or `.id`
);
```

Like the `.get` is important to turn it from a `ManyToOneReference` to an `Organization` (or `.id` to turn it into a `OrganizationId`).

I guess technically we could update the runtime to recognize a `Relation` coming in, and do the `.get` / `.id` internally--just really odd that this is not a compile error though.

Not sure whether to double-down on the current/expected API and find/fix the missing compile error, or lean into supporting this syntax as kosher, even if it is unintended.

I think I'll probably start with trying to make sure this is a compile error, because if we're letting this in unintentionally, we're potentially letting other types in unintentionally as well...

Thanks for reporting! I'll dig into this and try to find out what's happening.

**Comment by stephenh** [comment]
Just a small update, I remembered / rediscovered why this happens...

Joist's filter types are what TS calls "weak types" where every field is optional, i.e. firstName?, lastName?, etc.

Because of this, basically any type can technically structurally match an AuthorFilter or BookFilter etc. Even the {} empty type.

I've found a few tickets in the TS repo mentioning that they've tried to recognize these weal types, I believe by heuristics like "there are literally no overlap in keys between these two types".

But I'm not sure why those heuristics aren't working here. I'm still poking around though, and will hopefully find a good approach.

**Comment by stephenh** [comment]
https://github.com/microsoft/TypeScript/pull/16047 is what should have fixed our filter's weak type check, afaiu.

**Comment by stephenh** [comment]
Ah, turns out both `AuthorFilter` and `ManyToOneReference` have `id` fields, so that is just enough for TypeScript's structural typing to consider a `book.author`-that-is-a-`ManyToOneReference` to match the `AuthorFilter`.

If I just manually remove `AuthorFilter.id`, then I get the expected `TS2559: Type 'ManyToOneReference ' has no properties in common with type 'AuthorFilter'.` weak type error.
