### ISSUE TITLE
Populate on Collection.load

### ISSUE THREAD

**Issue by brudil** [stephenh/joist-ts#682]
Imagine UserAccount with FK to Organisation. UsersAccount might also have an FK to an Image.

```ts
organisation.usersAccounts.load(l => l.avatar) // Loaded<UserAccount, 'avatar'>[]
```

I might have missed something, but this seems like a nice QOL addition.

Edit: doesn't technically need to be a lens I guess, a populate/hint would work too!

**Comment by stephenh** [comment]
Ah yeah! That seems like a good idea. We've already got an `opts`-style overload on `load` (for `withDeleted` and `forceReload` opts), so it'd probably look like:

```
    const author = await book.author.load({ populate: "books" });
```

I'm a little surprised we don't have that already, so we might run into ... ah, yep:

![image](https://github.com/stephenh/joist-ts/assets/6401/93271dbf-cce4-49af-8d3a-4ad9da81a396)

Several times now when we've tried to add "load/populate" methods to ergonomic places directly within the domain model (instead of just in EntityManager.populate/load), for some reason TypeScript blows up on the entity types and starts thinking they're infinitely circular.

Which, the entity types are of course very interrelated (we have books pointing to authors pointing to books), but thankfully/so far as long as we keep them as "just books" and "just authors", everything has been fine.

But for whatever reason, adding more ways to `load`/populate a `Loaded<...>` type effectively introduces "populated books" and "populated authors" into the domain model's graph of types,  and ends up failing with this excessive type error.

I guess somehow we got it to work for `Author.populate` / `Book.populate`...maybe b/c we were able to codegen type-specific overloads in `AuthorCodegen` / `BookCodegen` files, but really I'm not sure why that worked, and these other attempts have failed.

I'll do a few more minutes of poking around at this, but we've yet to crack the "types are excessively" deep problem the last few times it's come up, so my guess is we'll have to keep this as a requested feature until either we get smarter or TS gets smarter. :-)

**Comment by brudil** [comment]
No worries if not, but if you've still got that branch, I wouldn't mind having a play around.

**Comment by stephenh** [comment]
Ah sure, just pushed the `add-populate-to-load` branch up.

**Comment by stephenh** [comment]
We can try to tackle this every once in awhile, but not anticipating it anytime soon.
