### ISSUE TITLE
Strings, not null & validation

### ISSUE THREAD

**Issue by brudil** [stephenh/joist-ts#704]
I think we might be hitting some incompatibailities with Joist's semantics and our schema.

For nullable text, we chose to represent this as a non null columns - ensuring that null is only ever represented by a single value `""`, vs allowing both `""` and `null` as two distinct representations of 'empty' with no semantic difference.

It looks like Joist takes a different approach here. Somewhere along the line, our default values of `""` are getting crushed to `undefined` or `null`. And thus triggering the `newRequiredRule`.

I'll keep digging to see where this is happening. And I guess a wider question for Joist - if this is intentional, is this a immovable schema design choice Joist has made or do you see the posiblity of a workaround/PR to support our schema?

Update: I see it's happening in setOpts https://github.com/stephenh/joist-ts/blob/9d268aacc52bd456e8aeff66fca2624340af49cb/packages/orm/src/index.ts#L159

-----

Perhaps the above coercion could be opted out of if the default value is set to ""? As that is essentially saying this is a blessed representation/value.

Alterantively I think we (in our codebase, not joist) could probably make use of a Serde here to provide the translate the undefined to a string, we would need a way to opt out of generating the newRequiredRule to replace with our own.

**Comment by stephenh** [comment]
Ah yep, I have the same dislike for `""` and `null` as two values of the same "empty" state, but went the other way, of picking `null` as the preferred empty value.

There are probably only ~3-4 places in the codebase (or maybe even just that one in `setOpts`, I'm not sure), but those places probably don't, at least right now, have easy/immediate access to a `config`-type instance to do conditional behavior.

I dunno, I'm like 9-out-of-10 would prefer to keep this as a Joist strong opinionated thing, that in the SQL world `null` is empty, so we should use `null`--similar to Joist's opinion on using only `undefined` for empty on the JS/TS side (instead of having the same "is JS empty `null` or `undefined`" confusion).

Also if I have a SQL field that is legitimately not-null, I find it irksome when I later query it and there are `""` values in it... And Joist's current behavior prevents that, it catches `""`, turns it into "the real empty of `undefined`/`null`", which then prevents the empty value from getting into the legitimately not-null column.

I guess thinking of it that way, the convention of "use '' for empty state in not-null columns" means you've lost the ability to differentiate, in your schema, actually required columns (like ideally should not even allow `""`, no empty values allowed) vs. optional columns (would be okay to have `""` in them) without some extra knowledge/conventions (like naming conventions or hints applied in the application code).

I think that nudges my 9-out-of-10 to like a 9.5-out-of-10 would prefer to not change this...

Your idea of doing a userland workaround like a custom serde is interesting--if that worked, that would be great.

Per the `newRequiredRule`, I could see a `joist-config.json` option that either turned off required rules or let the user provide their own--there the wrinkle would be I think the rules would still see the coerced-to-`undefined` value and not the serde-recovered `""` value. So you may not actually need to change the required rule--Joist internally would still be using `undefined` and it's only at the last minute you'd change it to `""` before going into the db schema. Maybe...

**Comment by stephenh** [comment]
> default value set to `""`

Ah, you mean in the db schema, the default column value is `""`? I guess that is a fair indication that the db schema expects empty strings...

**Comment by stephenh** [comment]
Hm, I guess if we moved the current coercion that is done in `setOpts` into the field setter, that would be a much easier place for the codegen to do configurable behavior, i.e. the correct logic would be baked into the codegen output, vs. `setOpts` needing to have some per-column/per-application runtime configuration.

**Comment by brudil** [comment]
> > default value set to `""`
> 
> Ah, you mean in the db schema, the default column value is `""`? I guess that is a fair indication that the db schema expects empty strings...

Indeed - bit of a gotcha as it currently is, because you can have a non-null column with a default value that gets picked up by `newRequiredRule`.

I think I'll evaluate the work for us to move over, as although it's work for us during this conversion, I also err on stuff like this being opinionated - especially when it's deeply intergrated.

It might be worth flagging this one in the Schema Assumptions doc page, as it would have helped us confront this much sooner.

**Comment by stephenh** [comment]
Cool! Fwiw my stance is softening a bit, just given:

1. The `default: ""` is a clear indicator from the db it is okay with `""` values
2. We could move the `"" -> empty` conversion from `setOpts` into setters to make it easy to conditionalize the behavior at codegen time (plus fix the bug I'd just noticed that setters are not doing this today)

Granted, even if we implement ^, agreed this is definitely worth a call-out in the Schema Assumptions page, to warn users about the `"" -> null` behavior, and that, if this is implemented, they can avoid it by using `default: ""` in their db schema.

**Comment by brudil** [comment]
> Cool! Fwiw my stance is softening a bit, just given:
> 
>     1. The `default: ""` is a clear indicator from the db it is okay with `""` values
> 
>     2. We could move the `"" -> empty` conversion from `setOpts` into setters to make it easy to conditionalize the behavior at codegen time (plus fix the bug I'd just noticed that setters are not doing this today)
> 
> 
> If you wanted to work on a PR to try this out, I think it'd be interesting to see how simple/complicated it ends up being to support.
> 
> Granted, even if we implement ^, agreed this is definitely worth a call-out in the Schema Assumptions page, to warn users about the `"" -> null` behavior, and that, if this is implemented, they can avoid it by using `default: ""` in their db schema.

We're at 44 usages of our current semantics, I'll discuss with the team and have a stab at that PR if we consider sticking. With the move to the setters; is this just the trim string check or the null too? As the null will stay no matter what. I assume it's if the aformentioned bug is there with null too?
