### ISSUE TITLE
Feature Request: Support Arrays

### ISSUE THREAD

**Issue by davekerber** [stephenh/joist-ts#822]
I am using a string array column with this schema: 

CREATE TABLE public.accounts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,  
    string_array_field character varying(32)[],
);

The metadata that is generated types stringArrayField as a string. 

It would be nice to use this with joist

**Comment by stephenh** [comment]
:+1:  We've had support for "enum array columns" for awhile, b/c we don't support m2m tables between entities and enums (for an entity to have a collection of enums), so we just used an `int[]` column instead.

We hadn't generalized that into "support for other primitive arrays", but looks like that was pretty easy, should be fixed in #826 .
