### ISSUE TITLE
Support singular table names

### ISSUE THREAD

**Issue by moltar** [stephenh/joist-ts#9]
I know I am picking nits here.

But I am still wondering. What is the underlying technical limitation for that?

**Comment by stephenh** [comment]
> What is the underlying technical limitation for that?

There is none, just simplicity/pragmaticism of picking/hardcoding what we're doing and not over-engineering before its really necessary.

I'd be open to some sort of `joist-codegen.json` setting to add a config setting like `tableNameStyle: "singular" | "plural"` as a default.

**Comment by moltar** [comment]
>  picking/hardcoding

But what are you picking or hardcoding?

Is there some magic under the hood that relies on things being plural?

That's what I am trying to understand.

In other words, what will happen if I don't use plural names?

**Comment by stephenh** [comment]
Ah sure. There is not any code at runtime that needs to guess table names, because there is a `metadata.ts` file with the domain object <-> table mapping specified.

Mostly it's used as codegen time, i.e. here:

https://github.com/stephenh/joist-ts/blob/b52076887340bc45ec54babe5f26daed137a8f6b/packages/codegen/src/utils.ts#L30

If you search for "pluralize" in the codebase, which is not very many, maybe ~2-3 of them are related to table names. So there is not very much, from scanning it looks like just "from a given table name, deriving the entity name" and maybe "when creating many to many tables, de-pluralizing the table names to make `table_a_id` / `table_b_id` columns".

So not a lot.

**Comment by stephenh** [comment]
We have a `joist-codegen.json` configuration file now that allows setting the table name, i.e.:

```
{
  "codegenPlugins": ["joist-graphql-codegen"],
  "contextType": "Context@src/context",
  "entities": {
    "Author": {
       "tableName": "author"
      "tag": "a"
    },
```

Would allow a singular `author` table name.
